version: "3"

services:
    jekyll:
        image: bretfisher/jekyll-serve
        volumes:
            - .:/site
            - cache:/usr/local/bundle
        ports:
            - "8080:4000"

    shell:
        image: bretfisher/jekyll
        volumes:
            - .:/site
            - cache:/usr/local/bundle
        ports:
            - "8080:4000"
        entrypoint: "bash"

volumes:
    cache:
